In [14]:
import torch
from torch import nn
import os
import numpy as np

In [55]:
class TransformerDecoder(nn.Module,):
    def __init__(self, *, vocab_size, target_pad_idx, d_model, feedforward, nhead):
        super(TransformerDecoder, self).__init__()
        n_layers = 1
        self.embedding = nn.Embedding(vocab_size, d_model)

        decoder_layer = nn.TransformerDecoderLayer(d_model, nhead, dim_feedforward=feedforward)

        self.decoder = nn.TransformerDecoder(decoder_layer, n_layers)


    def forward(self, target, memory):
        embedded = self.embedding(target)
        print(embedded.shape)
        decoded = self.decoder(embedded, memory)

        return decoded

In [62]:
vocab_size = 22
max_contexts = 7
batch_size = 4
embedding_size = 320

d_model = 320
feedforward = 512
embedding_dim = 128
nhead = 2
# memory = np.random.randint(vocab_size, size=(batch_size, max_contexts, embedding_size))
memory = torch.rand(max_contexts, batch_size , embedding_size)

target = torch.tensor(
    np.random.randint(vocab_size, size=(batch_size, max_contexts))
)

decoder = TransformerDecoder(vocab_size=vocab_size, d_model=d_model, feedforward=feedforward, nhead=nhead, target_pad_idx=0)
decoder(target, memory).shape

torch.Size([4, 7, 320])


torch.Size([4, 7, 320])

In [63]:
target.shape

torch.Size([4, 7])

In [59]:
a = torch.tensor([[
    [0.3, 0.9, 0.3],
    [0.2, 0.3, 0.8],
    [0.2, 0.3, 0.1]
],
    [
    [0.9, 0.9, 0.3],
    [0.2, 0.3, 0.8],
        [0.2, 0.3, 0.3]
    ]
])
import torch.nn.functional as F

In [60]:
a = F.softmax(a, dim=-1)
# 

In [61]:
a

tensor([[[0.2616, 0.4767, 0.2616],
         [0.2546, 0.2814, 0.4640],
         [0.3322, 0.3672, 0.3006]],

        [[0.3923, 0.3923, 0.2153],
         [0.2546, 0.2814, 0.4640],
         [0.3115, 0.3443, 0.3443]]])

In [70]:
vals, idx = a.topk(2, dim=-1)

In [71]:
idx

tensor([[[1, 0],
         [2, 1],
         [1, 0]],

        [[0, 1],
         [2, 1],
         [1, 2]]])

In [75]:
vals[idx[0]]

IndexError: index 2 is out of bounds for dimension 0 with size 2

In [76]:
idx[0]

tensor([[1, 0],
        [2, 1],
        [1, 0]])